/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LUXURY XI
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



public class bimblee extends javax.swing.JFrame {
    // === variabel global ===
    TableRowSorter<DefaultTableModel> sorter;
    // Harga Level
int hargaA1 = 1000000;
int hargaA2 = 1200000;
int hargaB1 = 1500000;
int hargaB2 = 1700000;
int hargaB3 = 1800000;
int hargaC1 = 2000000;

// Harga Jenis Kelas
int hargaReguler = 0;
int hargaIntensive = 500000;
int hargaPrivat = 1000000;
int hargaWeekend = 300000;
int hargaOnline = 200000;
 // ===================== BUTTON GROUP BARU UNTUK LEVEL =====================
    private ButtonGroup buttonGroupLevel = new ButtonGroup();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bimblee.class.getName());

    /**
     * Creates new form bimblee
     */
    public bimblee() {
        initComponents();
        

        

    // ==== GROUP JENIS KELAMIN ====
        buttonGroup1.add(rbLaki);
        buttonGroup1.add(rbPerempuan);

        // ==== GROUP LEVEL (BUAT BARU, TIDAK PAKAI BUTTONGROUP2 GUI) ====
        buttonGroupLevel.add(rbA1);
        buttonGroupLevel.add(rbA2);
        buttonGroupLevel.add(rbB1);
        buttonGroupLevel.add(rbB2);
        buttonGroupLevel.add(rbB3);
        buttonGroupLevel.add(rbC1);

        // ==== ISI COMBO TANGGAL ====
        for (int i = 1; i <= 30; i++) {
            comboTanggal.addItem(String.valueOf(i));
        }

        // ==== ISI COMBO BULAN ====
        String[] bulan = {
            "Januari", "Februari", "Maret", "April", "Mei",
            "Juni", "Juli", "Agustus", "September",
            "Oktober", "November", "Desember"
        };
        for (String b : bulan) comboBulan.addItem(b);

        // ==== ISI COMBO TAHUN ====
        for (int t = 2021; t <= 2025; t++) {
            comboTahun.addItem(String.valueOf(t));
        }
    }

    // ===================== FUNGSI AMBIL HARGA LEVEL =====================
    private int getHargaLevel(String level) {
        switch (level) {
            case "A1": return hargaA1;
            case "A2": return hargaA2;
            case "B1": return hargaB1;
            case "B2": return hargaB2;
            case "B3": return hargaB2; // ikut harga B2
            case "C1": return hargaC1;
            default: return 0;
        }
    }

    // ===================== FUNGSI AMBIL HARGA KELAS =====================
    private int getHargaJenisKelas(String kelas) {
        switch (kelas) {
            case "Reguler": return hargaReguler;
            case "Intensive": return hargaIntensive;
            case "Privat": return hargaPrivat;
            case "Weekend": return hargaWeekend;
            case "Online": return hargaOnline;
            default: return 0;
        }
    }

    // ===================== HITUNG TOTAL =====================
    private int hitungTotal(String level, String jenisKelas) {
        return getHargaLevel(level) + getHargaJenisKelas(jenisKelas);
    }
    
    // ===================== EVENT BUTTON SIMPAN =====================
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {

        // === Ambil Nama ===
        String nama = txtNama.getText();

        // === Ambil Tanggal ===
        String tgl = comboTanggal.getSelectedItem().toString();
        String bln = comboBulan.getSelectedItem().toString();
        String thn = comboTahun.getSelectedItem().toString();

        String tanggal = tgl + " " + bln + " " + thn;

        // === Ambil Paket ===
        String paket = comboPaket.getSelectedItem().toString();

        // === Ambil Kelas ===
        String kelas = comboJenisKelas.getSelectedItem().toString();

        // === Ambil Level ===
        String level = "";
        if (rbA1.isSelected()) level = "A1";
        if (rbA2.isSelected()) level = "A2";
        if (rbB1.isSelected()) level = "B1";
        if (rbB2.isSelected()) level = "B2";
        if (rbB3.isSelected()) level = "B3";
        if (rbC1.isSelected()) level = "C1";

        // === Hitung Harga ===
        int total = hitungTotal(level, kelas);

        // === TAMBAHKAN KE TABLE ===
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            nama, tanggal, paket, kelas, level, total
        });

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        comboTanggal = new javax.swing.JComboBox<>();
        comboBulan = new javax.swing.JComboBox<>();
        comboTahun = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboPaket1 = new javax.swing.JLabel();
        comboPaket = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rbA1 = new javax.swing.JRadioButton();
        rbA2 = new javax.swing.JRadioButton();
        rbB1 = new javax.swing.JRadioButton();
        rbB2 = new javax.swing.JRadioButton();
        rbC1 = new javax.swing.JRadioButton();
        rbB3 = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton1Tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("SISTEM BIMBLE BHS INGGRIS");

        txtNama1.setText("Nama");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel1.setText("Email");

        jLabel4.setText("No. Hp");

        jLabel8.setText("Jenis Kelamin");

        rbLaki.setText("Laki-laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });

        rbPerempuan.setText("Perempuan");

        jLabel9.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jLabel10.setText("Tanggal Daftar");

        comboTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " ", " " }));
        comboTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTanggalActionPerformed(evt);
            }
        });

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Febuary", "Maret", "April", "Juni", "Juli", "Agustus", "Oktober", "November", "Desember" }));
        comboBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBulanActionPerformed(evt);
            }
        });

        comboTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2021", "2022", "2023", "2024", "2025" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Program B");

        comboPaket1.setText("Paket");

        comboPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "1 Bulan", "3 Bulan", "6 Bulan", "12 Bulan", " ", " " }));

        jLabel7.setText("Level");

        rbA1.setText("A1 (Beginner)");
        rbA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbA1ActionPerformed(evt);
            }
        });

        rbA2.setText("A2 (Elementary)");
        rbA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbA2ActionPerformed(evt);
            }
        });

        rbB1.setText("B1 (Pre Intermediate)");
        rbB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbB1ActionPerformed(evt);
            }
        });

        rbB2.setText("B2 (Intermediate)");

        rbC1.setText("C1 (Advanced)");
        rbC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbC1ActionPerformed(evt);
            }
        });

        rbB3.setText("B3 (Upper-Intermediate)");
        rbB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbB3ActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas", "Reguler ", "Intensive", "Privat", "Weekend", "Online ", " ", " ", " ", " ", " " }));

        jLabel11.setText("Jenis Kelas");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton1Tambah.setText("Tambah");
        jButton1Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1TambahTambahActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal Daftar", "Paket", "Jenis Kelas", "Level", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rbLaki)
                                .addGap(18, 18, 18)
                                .addComponent(rbPerempuan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(comboPaket1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbA1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbA2)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbB1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 5, Short.MAX_VALUE)
                                        .addComponent(rbB3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbC1)
                                    .addComponent(rbB2))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton1Tambah))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Tambah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaket1)
                    .addComponent(comboPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbA1)
                    .addComponent(rbA2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbB2)
                    .addComponent(rbB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbC1)
                    .addComponent(rbB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void comboBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBulanActionPerformed

    private void rbA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbA1ActionPerformed

    private void rbA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbA2ActionPerformed
        // TODOadd your handling code here:
    }//GEN-LAST:event_rbA2ActionPerformed

    private void rbB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbB1ActionPerformed

    private void rbC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbC1ActionPerformed

    private void rbB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbB3ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
 int row = jTable1.getSelectedRow();
    if (row == -1) return;

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Update dari textfield ke tabel
    model.setValueAt(txtNama.getText(), row, 0);

    String tanggal = comboTanggal.getSelectedItem() + " " +
                     comboBulan.getSelectedItem() + " " +
                     comboTahun.getSelectedItem();
    model.setValueAt(tanggal, row, 1);

    model.setValueAt(comboPaket.getSelectedItem(), row, 2);
    model.setValueAt(cbKelas.getSelectedItem(), row, 3);

    String level = "";
    if (rbA1.isSelected()) level = "A1";
    else if (rbA2.isSelected()) level = "A2";
    else if (rbB1.isSelected()) level = "B1";
    else if (rbB2.isSelected()) level = "B2";
    else if (rbB3.isSelected()) level = "B3";
    else if (rbC1.isSelected()) level = "C1";

    model.setValueAt(level, row, 4);
     // === POPUP BERHASIL ===
    JOptionPane.showMessageDialog(this, 
            "Data berhasil diedit!", 
            "Sukses", 
            JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang mau dihapus!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.removeRow(row);

    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
// Clear text
    txtNama.setText("");
    txtEmail.setText("");
    jTextField3.setText("");
    txtAlamat.setText("");

    // Clear combo
    comboTanggal.setSelectedIndex(0);
    comboBulan.setSelectedIndex(0);
    comboTahun.setSelectedIndex(0);
    comboPaket.setSelectedIndex(0);
    cbKelas.setSelectedIndex(0);

    // Clear radio button
    buttonGroup1.clearSelection(); // kelamin
  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void comboTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTanggalActionPerformed

    private void jButton1TambahTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1TambahTambahActionPerformed
String nama = txtNama.getText();
    String tanggal = comboTanggal.getSelectedItem().toString() + " " +
                     comboBulan.getSelectedItem().toString() + " " +
                     comboTahun.getSelectedItem().toString();
    String paket = comboPaket.getSelectedItem().toString();
    String kelas = cbKelas.getSelectedItem().toString();

    String level = "";
    int hargaLevel = 0;

    if (rbA1.isSelected()) { level = "A1"; hargaLevel = hargaA1; }
    else if (rbA2.isSelected()) { level = "A2"; hargaLevel = hargaA2; }
    else if (rbB1.isSelected()) { level = "B1"; hargaLevel = hargaB1; }
    else if (rbB2.isSelected()) { level = "B2"; hargaLevel = hargaB2; }
    else if (rbB3.isSelected()) { level = "B3"; hargaLevel = hargaB3; }
    else if (rbC1.isSelected()) { level = "C1"; hargaLevel = hargaC1; }

    int hargaKelas = 0;

    switch (kelas.trim()) {
        case "Reguler": hargaKelas = hargaReguler; break;
        case "Intensive": hargaKelas = hargaIntensive; break;
        case "Privat": hargaKelas = hargaPrivat; break;
        case "Weekend": hargaKelas = hargaWeekend; break;
        case "Online": hargaKelas = hargaOnline; break;
    }

    int total = hargaLevel + hargaKelas;

    javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.addRow(new Object[]{
        nama,
        tanggal,
        paket,
        kelas,
        level,
        total
    });

    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1TambahTambahActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
String searchText = txtSearch.getText().trim();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Jika sorter belum dibuat, buat sekarang
    if (jTable1.getRowSorter() == null) {
        sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
    }

    // Jika kosong → tampilkan semua
    if (searchText.isEmpty()) {
        sorter.setRowFilter(null);
        JOptionPane.showMessageDialog(this, "Pencarian dikosongkan. Semua data ditampilkan.");
        return;
    }

    // Filter semua kolom, tidak case-sensitive
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));

    JOptionPane.showMessageDialog(this, "Pencarian untuk: " + searchText);
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bimblee().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<String> comboPaket;
    private javax.swing.JLabel comboPaket1;
    private javax.swing.JComboBox<String> comboTahun;
    private javax.swing.JComboBox<String> comboTanggal;
    private javax.swing.JButton jButton1Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton rbA1;
    private javax.swing.JRadioButton rbA2;
    private javax.swing.JRadioButton rbB1;
    private javax.swing.JRadioButton rbB2;
    private javax.swing.JRadioButton rbB3;
    private javax.swing.JRadioButton rbC1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtNama1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
